os:
- linux
- osx
compiler:
  - clang
language: c++
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - python-dev
    - python-numpy
    - libxml2-dev
    - libboost-all-dev
    - cmake

notifications:
  slack:
    rooms:
      - secure: Rxjp4bNLl/kx9dbQxpXtHi2KEl7M25/gJcG874IlF40B9tnPwRmGm+w8m3smQW7gRNLyZ6VfoBcmuGet+GMBTCCa44dCcm9qkx+OZJkOBv/C5TLEO4dBtAMFDhRRmpr2LhZfxvbC0R0CRP3wzGIea4RWFJBcvF/oAtGxYSfISpEE745DDY/W9yNRk3AchFDvb9T3f6ip3JDJnamdBh5xMUD1Ou6HiTUjXm4qrwwG89Lf9MrzmN3LOuP/+wE/w+wz4MeEYuPWMfQIYGdI0Bhz7zglmRpBPX4F6FSN9LyBrTORZz09erXLwcz7kyP+LfA3cXrvoMSD4eR8mSyRxV20o7p5+phHNdYkpohmoOwOPO7cT/yfSSjQIzCN4NYeIxTTXed4AyAfDFCVrB8o5sqs2QC1O7MuNOgKw1DDvUMNRLd+8x41xpdr0dZC1OxgJ0glURaHq1e7C2GqjzKgd0wm1bYhnOWWLMwe4S9mrxo8/bKG6JQ0TchXkr5PHo02QT+HTiDysDgsa+etyM4zIMbNpp3aYQsNMxu3IOgzINUgcnoVreyXlht1QGEu8I6WIWNWYnBmdjx+aK7V2dKeEx5LLqJ/RO5+CWaXyYIdg7EYQn/WIx9Z5ifCs4s8m7ZqKYd6D+1KpfrrhMtnZ/uTJ/HVHkLwyW7DX/caRn7kpnQU5Xc=
    template:
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)  %{result} in %{duration}"
      - "Author: %{author}   Repository@Branch: %{repository}@%{branch}"
      - "To package NFsim, please make a small modification to BioNetGen:"
      - "Web: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "


before_install:
- source osx_install.sh

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: 
  - mkdir -p build; mkdir -p dist; cd build; cmake ..; make; cp NFsim ../dist; cd ..; 
  - cd validate;tar xfj bionetgen-2.2.6.tar.bz2
  - python validate.py
  - cd ..
  
before_deploy:
  - cd dist; python changeFilename.py; cd ..

#deploy:
#  provider: s3
#  access_key_id:
#    secure: ctz/+kLFTn38ccVJpChZ8D8VKqrV7DGaLAxKKZaIAuvW/f3Cvccou5V98T8yJRHStfBCILZ/hkmnXMWLNayzvGTtffzNNL0U8X+IY9NFkplB89+7mZ1+16mc2wos2cFzlu7Mj9yBZm2rPGfmg69uWreo6xW17+aZdqVXw1bXbHQYdKlxCw1N5FwZu8GYtdmnMMk7HXssqrh7Xyo90iiFY3upKlhu2gCZz4OU3T77GGVNKR0ABv4lCriJxMMnz3jVKgZYvBYFBP6qKYCElBim1bv4r/jxZvhXZUN6DJ0HvKvFBXsq8vuZNT3sjBDbb6upIdmsaPDAh1ZTFOXkdLoL8M5TLq7F4aUSCp4tvKW/Ckk5KKQRwuh7h+LVzi+0Qo9HPysF/QWxfRzzhRgNhwR7E+qYtEwjNsh0hk1blJzCU8FrigZ/3zJNgGAaXS8HVodXhrQ0VDUrEuu28yBoPdjUvlgt15tyWAeHby0VxxMz5hOQtCjKEIECbNBpG2g7dC6s3C+jE2O+VMtEktxFQF5aZzLeqoMvOacCE85IC9Sv9WTgihdmURORI0JlKOG+M+UJdAjZUK6DSO8PenbgHH5CKiKiF2TPVesXKnw0tAmHtfsJWBkq5mBHfBpB9SLi+bsGWBkR4j86GSZ/q+K6Kxi444vm1CFXcF3J6oJLVRnHPas=
#  secret_access_key:
#    secure: IHOpj+ZIB9+8ES4q0/cUHuc5Pby7JYsLtkMSeo6k2jZQh9mb1GQ/kkpdfzKnLp2Tvlt+I7wCIsx3NqsaBNwa0OHVgREIHjtTtC+I8ueVBiPsn0hEZ5RHJA+2DRzAaXoq1fHd4IC92j3RT4qLQKjc9ochlB0FhCHs7N/RM62dtlFLYGWv9lPk9ZbI0OZHI25vDnG8aaaVwYeqIe71kHo/GgSUhM2NSFKvQkmlktKeb1a5hTc0X8x0S5XuFGnKzAV3rpgIj7bVDnuraTV2wtuleT8klwNqCJhIAVkz39hhIWPNVumzq77RnDvgsH9BuSHNia+NDUcEq9judODxTmsF0BIxCQb13LfDRbl+zRwnhrHGv+vk33zsQ6Zom3A3skJqLftv01y72FplLuJSp4jvw4J1wuAPWUpkeriHfgJSl1ZWOl4cLBL+/LeYm2NI5KdCguslVErLF/FuJbC2QUlqEl7a9HHmyOuk5CPvrMUKkAW8cue9AJDtW20yyWqXqZAryCQD3KX8C7EnYxxy5kACSIkGB5TBgcdP3r9OmkWtj9vE5EA49qMAr97l5UYc7TDLkdh6hhaIZzsA9NfhvAx/++lNVn7tiwXPUU+XeKQKDw0zY+6c1e8oNE0k/8kOCU/qgjcw+UZWERQPC4+M0jCRSl0Na5AirpjmyD2onHedIa8=
#  bucket: nfsim
#  skip_cleanup: true
#  local_dir: dist
#  on:
#    branch: release
